/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_tinder_studio_AndroidGLView */

#ifndef _Included_org_tinder_studio_AndroidGLView
#define _Included_org_tinder_studio_AndroidGLView
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_tinder_studio_AndroidGLView
 * Method:    nativeInit
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_tinder_studio_AndroidGLView_nativeInit
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_tinder_studio_AndroidGLView
 * Method:    nativeResize
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_tinder_studio_AndroidGLView_nativeResize
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_tinder_studio_AndroidGLView
 * Method:    nativeRender
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_tinder_studio_AndroidGLView_nativeRender
  (JNIEnv *, jobject);

/*
 * Class:     org_tinder_studio_AndroidGLView
 * Method:    nativePress
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_org_tinder_studio_AndroidGLView_nativePress
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     org_tinder_studio_AndroidGLView
 * Method:    nativeRelease
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_org_tinder_studio_AndroidGLView_nativeRelease
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     org_tinder_studio_AndroidGLView
 * Method:    nativeDone
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_tinder_studio_AndroidGLView_nativeDone
  (JNIEnv *, jobject);

/*
 * Class:     org_tinder_studio_AndroidGLView
 * Method:    nativeOnBackDown
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_tinder_studio_AndroidGLView_nativeOnBackDown
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
