/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_demo_list_examples_Example00 */

#ifndef _Included_com_demo_list_examples_Example00
#define _Included_com_demo_list_examples_Example00
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_demo_list_examples_Example00
 * Method:    demo
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_demo_list_examples_Example00_demo
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
