/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_tinder_studio_gl_AndroidGLView */

#ifndef _Included_org_tinder_studio_gl_AndroidGLView
#define _Included_org_tinder_studio_gl_AndroidGLView
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_tinder_studio_gl_AndroidGLView_AndroidGLRender */

#ifndef _Included_org_tinder_studio_gl_AndroidGLView_AndroidGLRender
#define _Included_org_tinder_studio_gl_AndroidGLView_AndroidGLRender
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_tinder_studio_gl_AndroidGLView_AndroidGLRender
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_tinder_studio_gl_AndroidGLView_nativeInit
  (JNIEnv *env, jobject thiz, jstring apkPath);

/*
 * Class:     org_tinder_studio_gl_AndroidGLView_AndroidGLRender
 * Method:    nativeResize
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_tinder_studio_gl_AndroidGLView_nativeResize
  (JNIEnv *env, jobject thiz, jint w, jint h);

/*
 * Class:     org_tinder_studio_gl_AndroidGLView_AndroidGLRender
 * Method:    nativeRender
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_tinder_studio_gl_AndroidGLView_nativeRender
  (JNIEnv *env, jobject thiz);

/*
 * Class:     org_tinder_studio_gl_AndroidGLView_AndroidGLRender
 * Method:    nativeDone
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_tinder_studio_gl_AndroidGLView_nativeDone
  (JNIEnv *env, jobject thiz);

/*
 * Class:     org_tinder_studio_gl_AndroidGLView_AndroidGLRender
 * Method:    nativePause
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_tinder_studio_gl_AndroidGLView_nativePause
  (JNIEnv *env, jobject thiz);

#ifdef __cplusplus
}
#endif
#endif
