/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_tinder_studio_gl_HelloGLView */

#ifndef _Included_org_tinder_studio_gl_HelloGLView
#define _Included_org_tinder_studio_gl_HelloGLView
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_tinder_studio_gl_HelloGLView_HelloGLRender */

#ifndef _Included_org_tinder_studio_gl_HelloGLView_HelloGLRender
#define _Included_org_tinder_studio_gl_HelloGLView_HelloGLRender
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_tinder_studio_gl_HelloGLView_HelloGLRender
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_tinder_studio_gl_HelloGLView_nativeInit
  (JNIEnv *env, jobject thiz);

/*
 * Class:     org_tinder_studio_gl_HelloGLView_HelloGLRender
 * Method:    nativeResize
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_tinder_studio_gl_HelloGLView_nativeResize
  (JNIEnv *env, jobject thiz, jint w, jint h);

/*
 * Class:     org_tinder_studio_gl_HelloGLView_HelloGLRender
 * Method:    nativeRender
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_tinder_studio_gl_HelloGLView_nativeRender
  (JNIEnv *env, jobject thiz);

/*
 * Class:     org_tinder_studio_gl_HelloGLView_HelloGLRender
 * Method:    nativeDone
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_tinder_studio_gl_HelloGLView_nativeDone
  (JNIEnv *env, jobject thiz);

#ifdef __cplusplus
}
#endif
#endif
