#ifndef _YON_VIDEO_OGLES1_EGLINFO_H_
#define _YON_VIDEO_OGLES1_EGLINFO_H_

#include "yonConfig.h"

#ifdef YON_COMPILE_WITH_WIN32

#include "yonString.h"
#include "yonMap.h"

namespace yon{
namespace video{
namespace ogles1{

	class EGLInfo{
	private:
		EGLInfo(){}
		EGLInfo(const EGLInfo& info){}
		EGLInfo& operator = (const EGLInfo&){}
	public:
		core::map<u16,core::stringc> EGL_NAME_FLAGS;
		core::map<u16,core::stringc> EGL_SURFACE_FLAGS;
		core::map<u16,core::stringc> EGL_RENDERABLE_FLAGS;
		core::map<u16,core::stringc> EGL_ERROR_FLAGS;

		static EGLInfo& getInstance(){
			static EGLInfo info;
			return info;
		}

		void init();
		void destroy();
	};

	void EGLInfo::destroy(){
		EGL_NAME_FLAGS.clear();
		EGL_SURFACE_FLAGS.clear();
		EGL_RENDERABLE_FLAGS.clear();
		EGL_ERROR_FLAGS.clear();
	}

	
	void EGLInfo::init(){
		
		EGL_NAME_FLAGS[EGL_RED_SIZE]="EGL_RED_SIZE";
		//EGL_NAME_FLAGS.set(EGL_RED_SIZE,"EGL_RED_SIZE");
		EGL_NAME_FLAGS[EGL_GREEN_SIZE]="EGL_GREEN_SIZE";
		EGL_NAME_FLAGS[EGL_BLUE_SIZE]="EGL_BLUE_SIZE";
		EGL_NAME_FLAGS[EGL_ALPHA_SIZE]="EGL_ALPHA_SIZE";
		EGL_NAME_FLAGS[EGL_BUFFER_SIZE]="EGL_BUFFER_SIZE";
		//EGL_NAME_FLAGS[EGL_SURFACE_TYPE]="EGL_SURFACE_TYPE";
		EGL_NAME_FLAGS[EGL_DEPTH_SIZE]="EGL_DEPTH_SIZE";
		EGL_NAME_FLAGS[EGL_STENCIL_SIZE]="EGL_STENCIL_SIZE";
		EGL_NAME_FLAGS[EGL_SAMPLE_BUFFERS]="EGL_SAMPLE_BUFFERS";
		EGL_NAME_FLAGS[EGL_SAMPLES]="EGL_SAMPLES";
		//EGL_NAME_FLAGS[EGL_RENDERABLE_TYPE]="EGL_RENDERABLE_TYPE";
		EGL_NAME_FLAGS[EGL_NONE]="EGL_NONE";

		EGL_SURFACE_FLAGS[EGL_PBUFFER_BIT]="EGL_PBUFFER_BIT";
		EGL_SURFACE_FLAGS[EGL_PIXMAP_BIT]="EGL_PIXMAP_BIT";
		EGL_SURFACE_FLAGS[EGL_WINDOW_BIT]="EGL_WINDOW_BIT";
		EGL_SURFACE_FLAGS[EGL_VG_COLORSPACE_LINEAR_BIT]="EGL_VG_COLORSPACE_LINEAR_BIT";
		EGL_SURFACE_FLAGS[EGL_VG_ALPHA_FORMAT_PRE_BIT]="EGL_VG_ALPHA_FORMAT_PRE_BIT";
		EGL_SURFACE_FLAGS[EGL_MULTISAMPLE_RESOLVE_BOX_BIT]="EGL_MULTISAMPLE_RESOLVE_BOX_BIT";
		EGL_SURFACE_FLAGS[EGL_SWAP_BEHAVIOR_PRESERVED_BIT]="EGL_SWAP_BEHAVIOR_PRESERVED_BIT";

		EGL_RENDERABLE_FLAGS[EGL_OPENGL_ES_BIT]="EGL_OPENGL_ES_BIT";
		EGL_RENDERABLE_FLAGS[EGL_OPENVG_BIT]="EGL_OPENVG_BIT";
		EGL_RENDERABLE_FLAGS[EGL_OPENGL_ES2_BIT]="EGL_OPENGL_ES2_BIT";
		EGL_RENDERABLE_FLAGS[EGL_OPENGL_BIT]="EGL_OPENGL_BIT";

		EGL_ERROR_FLAGS[EGL_SUCCESS]="EGL_SUCCESS";
		EGL_ERROR_FLAGS[EGL_NOT_INITIALIZED]="EGL_NOT_INITIALIZED";
		EGL_ERROR_FLAGS[EGL_BAD_ACCESS]="EGL_BAD_ACCESS";
		EGL_ERROR_FLAGS[EGL_BAD_ALLOC]="EGL_BAD_ALLOC";
		EGL_ERROR_FLAGS[EGL_BAD_ATTRIBUTE]="EGL_BAD_ATTRIBUTE";
		EGL_ERROR_FLAGS[EGL_BAD_CONFIG]="EGL_BAD_CONFIG";
		EGL_ERROR_FLAGS[EGL_BAD_CONTEXT]="EGL_BAD_CONTEXT";
		EGL_ERROR_FLAGS[EGL_BAD_CURRENT_SURFACE]="EGL_BAD_CURRENT_SURFACE";
		EGL_ERROR_FLAGS[EGL_BAD_DISPLAY]="EGL_BAD_DISPLAY";
		EGL_ERROR_FLAGS[EGL_BAD_MATCH]="EGL_BAD_MATCH";
		EGL_ERROR_FLAGS[EGL_BAD_NATIVE_PIXMAP]="EGL_BAD_NATIVE_PIXMAP";
		EGL_ERROR_FLAGS[EGL_BAD_NATIVE_WINDOW]="EGL_BAD_NATIVE_WINDOW";
		EGL_ERROR_FLAGS[EGL_BAD_PARAMETER]="EGL_BAD_PARAMETER";
		EGL_ERROR_FLAGS[EGL_BAD_SURFACE]="EGL_BAD_SURFACE";
		EGL_ERROR_FLAGS[EGL_CONTEXT_LOST]="EGL_CONTEXT_LOST";
		
	}
	
}
}
}
#endif
#endif