#ifndef _YON_VIDEO_OGLES1_EGLINFO_H_
#define _YON_VIDEO_OGLES1_EGLINFO_H_

#include "yonConfig.h"

#ifdef YON_COMPILE_WITH_WIN32

#include "yonString.h"
#include "yonMap.h"

namespace yon{
namespace video{
namespace ogles1{

	class EGLInfo{
	public:
		static core::map<u16,core::stringc> EGL_NAME_FLAGS;
		static core::map<u16,core::stringc> EGL_SURFACE_FLAGS;
		static core::map<u16,core::stringc> EGL_RENDERABLE_FLAGS;

		void static init();
	};

	core::map<u16,core::stringc> EGLInfo::EGL_NAME_FLAGS;
	core::map<u16,core::stringc> EGLInfo::EGL_SURFACE_FLAGS;
	core::map<u16,core::stringc> EGLInfo::EGL_RENDERABLE_FLAGS;

	void EGLInfo::init(){
		EGL_NAME_FLAGS[EGL_RED_SIZE]="EGL_RED_SIZE";
		//EGL_NAME_FLAGS.set(EGL_RED_SIZE,"EGL_RED_SIZE");
		EGL_NAME_FLAGS[EGL_GREEN_SIZE]="EGL_GREEN_SIZE";
		EGL_NAME_FLAGS[EGL_BLUE_SIZE]="EGL_BLUE_SIZE";
		EGL_NAME_FLAGS[EGL_ALPHA_SIZE]="EGL_ALPHA_SIZE";
		EGL_NAME_FLAGS[EGL_BUFFER_SIZE]="EGL_BUFFER_SIZE";
		//EGL_NAME_FLAGS[EGL_SURFACE_TYPE]="EGL_SURFACE_TYPE";
		EGL_NAME_FLAGS[EGL_DEPTH_SIZE]="EGL_DEPTH_SIZE";
		EGL_NAME_FLAGS[EGL_STENCIL_SIZE]="EGL_STENCIL_SIZE";
		EGL_NAME_FLAGS[EGL_SAMPLE_BUFFERS]="EGL_SAMPLE_BUFFERS";
		EGL_NAME_FLAGS[EGL_SAMPLES]="EGL_SAMPLES";
		//EGL_NAME_FLAGS[EGL_RENDERABLE_TYPE]="EGL_RENDERABLE_TYPE";
		EGL_NAME_FLAGS[EGL_NONE]="EGL_NONE";

		EGL_SURFACE_FLAGS[EGL_PBUFFER_BIT]="EGL_PBUFFER_BIT";
		EGL_SURFACE_FLAGS[EGL_PIXMAP_BIT]="EGL_PIXMAP_BIT";
		EGL_SURFACE_FLAGS[EGL_WINDOW_BIT]="EGL_WINDOW_BIT";
		EGL_SURFACE_FLAGS[EGL_VG_COLORSPACE_LINEAR_BIT]="EGL_VG_COLORSPACE_LINEAR_BIT";
		EGL_SURFACE_FLAGS[EGL_VG_ALPHA_FORMAT_PRE_BIT]="EGL_VG_ALPHA_FORMAT_PRE_BIT";
		EGL_SURFACE_FLAGS[EGL_MULTISAMPLE_RESOLVE_BOX_BIT]="EGL_MULTISAMPLE_RESOLVE_BOX_BIT";
		EGL_SURFACE_FLAGS[EGL_SWAP_BEHAVIOR_PRESERVED_BIT]="EGL_SWAP_BEHAVIOR_PRESERVED_BIT";

		EGL_RENDERABLE_FLAGS[EGL_OPENGL_ES_BIT]="EGL_OPENGL_ES_BIT";
		EGL_RENDERABLE_FLAGS[EGL_OPENVG_BIT]="EGL_OPENVG_BIT";
		EGL_RENDERABLE_FLAGS[EGL_OPENGL_ES2_BIT]="EGL_OPENGL_ES2_BIT";
		EGL_RENDERABLE_FLAGS[EGL_OPENGL_BIT]="EGL_OPENGL_BIT";
	}
}
}
}
#endif
#endif