/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class yon_AndroidGLView */

#ifndef _Included_yon_AndroidGLView
#define _Included_yon_AndroidGLView
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     yon_AndroidGLView
 * Method:    nativeOnSurfaceCreated
 * Signature: (ZIILjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_yon_AndroidGLView_nativeOnSurfaceCreated
  (JNIEnv *, jobject, jboolean, jint, jint, jstring, jstring);

/*
 * Class:     yon_AndroidGLView
 * Method:    nativeOnSurfaceChanged
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_yon_AndroidGLView_nativeOnSurfaceChanged
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     yon_AndroidGLView
 * Method:    nativeOnDrawFrame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_yon_AndroidGLView_nativeOnDrawFrame
  (JNIEnv *, jobject);

/*
 * Class:     yon_AndroidGLView
 * Method:    nativeOnPause
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_yon_AndroidGLView_nativeOnPause
  (JNIEnv *, jobject);

/*
 * Class:     yon_AndroidGLView
 * Method:    nativeOnResume
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_yon_AndroidGLView_nativeOnResume
  (JNIEnv *, jobject);

/*
 * Class:     yon_AndroidGLView
 * Method:    nativeOnDestroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_yon_AndroidGLView_nativeOnDestroy
  (JNIEnv *, jobject);

/*
 * Class:     yon_AndroidGLView
 * Method:    nativeOnBack
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_yon_AndroidGLView_nativeOnBack
  (JNIEnv *, jobject);

/*
 * Class:     yon_AndroidGLView
 * Method:    nativeOnTouch
 * Signature: (IIFFI)Z
 */
JNIEXPORT jboolean JNICALL Java_yon_AndroidGLView_nativeOnTouch
  (JNIEnv *, jobject, jint, jint, jfloat, jfloat, jint);

/*
 * Class:     yon_AndroidGLView
 * Method:    nativeOnMove
 * Signature: (I[I[F[FI)Z
 */
JNIEXPORT jboolean JNICALL Java_yon_AndroidGLView_nativeOnMove
  (JNIEnv *, jobject, jint, jintArray, jfloatArray, jfloatArray, jint);

/*
 * Class:     yon_AndroidGLView
 * Method:    nativeOnUI
 * Signature: (I[Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_yon_AndroidGLView_nativeOnUI
  (JNIEnv *, jobject, jint, jobjectArray);

/*
 * Class:     yon_AndroidGLView
 * Method:    nativeDebug
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_yon_AndroidGLView_nativeDebug
  (JNIEnv *, jobject, jstring);

/*
 * Class:     yon_AndroidGLView
 * Method:    nativeInfo
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_yon_AndroidGLView_nativeInfo
  (JNIEnv *, jobject, jstring);

/*
 * Class:     yon_AndroidGLView
 * Method:    nativeWarn
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_yon_AndroidGLView_nativeWarn
  (JNIEnv *, jobject, jstring);

/*
 * Class:     yon_AndroidGLView
 * Method:    nativeError
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_yon_AndroidGLView_nativeError
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
